VVINSTALLPATH='__VVINSTALLPATH__';

VVUTILSPATH=sprintf('%s/utils', VVINSTALLPATH);
VVTESTSPATH=sprintf('%s/tests', VVINSTALLPATH);

addpath(VVINSTALLPATH);
addpath(VVTESTSPATH);
addpath(VVUTILSPATH);
