%HOW TO ADD A NEW AC ANALYSIS TEST FOR A CIRCUIT DAE
%
%MAPPtest for the AC analysis test is carried out by running the script
%MAPPtest_AC.m, which in turn calls the function "generate_all_AC_tests()".
%This function creates a MATLAB cell array object "alltests" containing
%information about the circuit DAEs on which AC analysis test is to be carried
%out. It also contains various parameters needed to run the AC analysis test.
%Then, another function "test_AC()" is called iteratively on each circuit in
%"alltests". 
%
%A new AC analysis test can be added by modifying the function
%"generate_all_AC_tests()" with the following workflow.
%
%1. Before adding a new test to the MAPP AC test system, write a MATLAB
%   script which successfully runs the new AC analysis on the corresponding
%   circuit DAE. Run that script and verify the correctness of the simulation
%   result.  There is no recommended way to do this check. However, there are
%   several standard ways in which this check can be performed, e.g., by doing
%   hand-calculation, comparing the MAPP simulation result against in-house or
%   published experimental data or against simulation output of a simulator
%   which you trust, etc.   
%
%2. Modify the script
%   "MAPP-ROOT/A1oDAEAPI-MATLAB/generate_all_AC_tests.m" as per the
%   instructions provided below.
%
%   a. Find out how many testcases are being generated by
%      generate_all_AC_case(). Say that there are 26 testcases being
%      generated and the new test you want to add is the 27th. Go to the end of
%      the script and add the following line.
%
%      function out = generate_testcase27()
%
%   b. Generate the circuit DAE by calling the appropriate MATLAB script and
%      assign it to "test.DAE".
%
%      EXAMPLE:
%      test.DAE = BJTdiffpair_DAEAPIv6('BJT-differential-pair');
%
%      In the above example, the generated reference test data will be stored
%      in a MATLAB .mat file "BJT-differential-pair_AC.mat". So, please
%      pay close attention while choosing this unique string ID so that none of
%      the existing reference data .mat files are over-written in the process.
%
%      You should replace the line noted in the above example with one which
%      calls the circuit DAE noted in step 1. 
%
%   c. Set up the input function(s) for the AC analysis 
%
%      EXAMPLE:
%      Ufargs.string = 'no args used'; 
%      Uffunc = @(f, args) 1; % constant U(j 2 pi f) \equiv 1
%      test.DAE = feval(test.DAE.set_uLTISSS, Uffunc, Ufargs, test.DAE);
%
%      These input functions should be the same as the ones in the MATLAB
%      script noted in step 1.
%
%   d. Set up the DC operating point and the initial guess and assign them to
%      the appropriate fields in "test.testargs".
%
%      EXAMPLE:
%      test.testargs.DCOP = 0; % DC operating point
%      test.testargs.initguess=feval(test.DAE.QSSinitGuess, ...
%                test.testargs.DCOP, test.DAE);
%
%      These parameters should be the same as those in the MATLAB script noted
%      in step 1.
%
%   e. Set up AC simulation parameters and assign them to the appropriate
%      fields in "test.testargs.ACparms". 
%      
%      EXAMPLE:
%       test.testargs.ACparms.sweeptype = 'DEC'; % Sweeptype 
%       test.testargs.ACparms.fstart = 1; % Start frequency
%       test.testargs.ACparms.fstop = 1e5; % Stop frequency 
%       test.testargs.ACparms.nsteps = 10; % No. of steps
%
%      These parameters should be the same as those in the MATLAB script noted
%      in step 1.
%
%   f. Add the following three lines to your code.
%      
%      test.testargs.updateReference = 1; 
%      test.testargs.LogMsgDisplay = 1; 
%      end
%
%      Save the script and exit.
%
%   g. Open the script 
%      "MAPP-ROOT/A1oDAEAPI-MATLAB/MAPPtest_AC.m" and find the following
%      line -
%
%           alltests = generate_all_AC_tests();
%
%      Replace that line with the following:
%
%           alltests = generate_all_AC_tests(27);
%
%      Save the script and exit.
%
%3. Go to the MATLAB command line and run the script "MAPPtest_AC". Upon
%   successful execution, the input data, the output data and the parameter
%   values pertinent to the AC test will be saved in a .mat MATLAB file
%   as reference test data. This data will be used as a reference to compare
%   against while running MAPPtest_AC in the compare/test mode.
%
%4. Open the script 
%      "MAPP-ROOT/A1oDAEAPI-MATLAB/MAPPtest_AC.m" and find the line:
%
%           alltests = generate_all_AC_tests(27);
%
%   Replace that line with the following line: 
%
%           alltests = generate_all_AC_tests();
%
%   Save the script and exit.
%
%5. Open the script 
%      "MAPP-ROOT/A1oDAEAPI-MATLAB/generate_all_AC_tests.m" 
%
%   and find the following lines: 
%
%      test.testargs.updateReference = 1; 
%      test.testargs.LogMsgDisplay = 1; 
%
%   Replace them with the following two lines:
%
%      test.testargs.updateReference = 0; 
%      test.testargs.LogMsgDisplay = 0; 
%
%6. Then find the following line:
%    
%    no_of_circuits = 26;
%
%   Replace that with the following line:
%
%    no_of_circuits =27;
%
%   Save the script and exit.
