function out = Rsource(t, tau, T)
% 2-d autocorrelation function of a stochastic process
%	generated by linear interpolation between 
%	independent identical random variables, uniformly spaced T apart.

if (t<0)
	n = ceil(abs(t/T));
	t = t + n*T;
elseif (t>T)
	n = floor(t/T);
	t = t - n*T;
end

if (t<=-T-tau)
	out = 0;
elseif (t<=-tau)
	out = (1-t/T)*(1+(t+tau)/T);
elseif (t<=T-tau)
	out = (1-t/T)*(1-(t+tau)/T) + t/T*(t+tau)/T;
elseif (t<=2*T-tau)
	out = t/T*(1-(t+tau-T)/T);
else
	out = 0;
end
