function test = STA_SHdiffpair_transient()

	% Author: Bichen Wu
	% Date: 05/06/2014
	% Moved from test_STAEqnEngine_SH_MOSdiffpair_DC_AC_tran.m
	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    % Circuit DAE
	STAEqnEngine_SH_MOSdiffpair;
	DAE = feval(DAE.set_uQSS, 'Vin:::E', 0, DAE);
	DAE = feval(DAE.set_uQSS, 'vdd:::E', 5, DAE);
	DAE = feval(DAE.set_uQSS, 'IS:::I', 2e-3, DAE);

	args.f = 1000;
	args.A = 0.5;
	sinfunc = @(t, args) args.A*sin(args.f*2*pi*t);
	DAE = feval(DAE.set_utransient, 'Vin:::E', sinfunc, args, DAE);
	DAE = feval(DAE.set_utransient, 'vdd:::E', @(t,a) 5, [], DAE);
	DAE = feval(DAE.set_utransient, 'IS:::I', @(t,a) 2e-3, [], DAE);

	DAE = feval(DAE.setparms, 'R1:::R', 500, DAE);
	DAE = feval(DAE.setparms, 'R2:::R', 500, DAE);
	DAE = feval(DAE.setparms, 'C1:::C', 0.1e-6, DAE);
	DAE = feval(DAE.setparms, 'C2:::C', 0.1e-6, DAE);
	DAE = feval(DAE.set_utransient, 'IS:::I', @(t,a) 8e-3, [], DAE);
	

    test.DAE = DAE;
    test.name = 'STA_SHdiffpair_tran'; % Type of analysis
    test.analysis = 'transient'; % Type of analysis
    test.refFile = 'STA_SHdiffpair_tran.mat';

    % Simulation time-related parameters
    test.args.xinit = [ ...
 					   5.0000; ...
 					   3.0000; ...
 					   3.0000; ...
 					  -0.6162; ...
 					        0; ...
 					   5.0000; ...
 					        0; ...
 					  -0.6162; ...
 					   2.0000; ...
 					   2.0000; ...
 					   2.0000; ...
 					   2.0000; ...
 					   3.6162; ...
 					   0.6162; ...
 					   3.6162; ...
 					   0.6162; ...
 					  -0.0020; ...
 					        0; ...
 					   0.0020; ...
 					   0.0010; ...
 					        0; ...
 					   0.0010; ...
 					        0; ...
 					   0.0010; ...
 					        0; ...
 					   0.0010; ...
 					        0; ...
					  ];


    % [3; 3; -0.5]; % Initial condition
    test.args.tstart = 0;           % Start time
    test.args.tstep = 2e-5;        % Time step
    test.args.tstop = 2e-3;         % Stop time
    % Transient simulation parameters
    test.args.tranparms = defaultTranParms; % Transient simulation
    test.args.tranparms.NRparms.limiting = 1; 
    test.args.tranparms.doStepControl = 1;
    % Any changes to default tranparms setting
    test.args.tranparms.trandbglvl = -1; % Only errors 
    % LMS method to be used
    test.args.LMSMethod = 'GEAR2'; % {'BE','FE','TRAP','GEAR2'}
    % Update or testing/comparison
    % test.args.LogMsgDisplay = 0; % 1 = verbose, 0 = non-verbose
end

